#pokeys configuration example
pokeys:
  devices:
    - name: "PoKeys57E_device_1"
      serial: 31557
      buttons:
        - name: "pokeys_button_1"
          pin: 13
          delay: 4 #describes how long(seconds) the button will be turned on after press is called
        - name: "pokeys_button_2"
          pin: 12
          delay: 2
      binary_sensors:
        - name: "pokeys_binary_sensor"
          pin: 8
    - name: "PoKeys57E_device_2"
      serial: 31708
      sensors:
        - name: "pokeys_easy_sensor_temperature"
          id: 0 #sensor id/index
      switches:
        - name: "pokeys_switch"
          pin: 12

#supported entities: switch, button, sensor(for pokeys EasySensor), binary_sensor