switch:
  - platform: pokeys
    name: "PoKeys57E"
    serial: "31557"
    pin: "12"
  #- platform: pokeys  (syntax for multiple switch entities)
  #  name: "PoKeys57E_2"
  #  host: "192.168.1.105"

button:
  - platform: pokeys
    name: "PoKeys57E"
    serial: "31557"
    pin: "13"

binary_sensor:
  - platform: pokeys
    name: "PoKeys57E"
    serial: "31557"
    pin: "8"

sensor:
  - platform: pokeys
    name: "PoKeys57E"
    serial: "31557"
